# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NE_Dialog.ui'
#
# Created: Thu Sep 26 20:17:15 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(309, 265)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonOK = QtGui.QPushButton(Dialog)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.gridLayout_2.addWidget(self.pushButtonOK, 1, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.labelNE = QtGui.QLabel(self.groupBox_3)
        self.labelNE.setObjectName("labelNE")
        self.gridLayout.addWidget(self.labelNE, 0, 0, 1, 1)
        self.lineEditNE = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditNE.setObjectName("lineEditNE")
        self.gridLayout.addWidget(self.lineEditNE, 0, 1, 1, 1)
        self.labelIP = QtGui.QLabel(self.groupBox_3)
        self.labelIP.setObjectName("labelIP")
        self.gridLayout.addWidget(self.labelIP, 1, 0, 1, 1)
        self.lineEditIP = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditIP.setObjectName("lineEditIP")
        self.gridLayout.addWidget(self.lineEditIP, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 2)
        self.labelManageUser = QtGui.QLabel(self.groupBox_3)
        self.labelManageUser.setObjectName("labelManageUser")
        self.gridLayout.addWidget(self.labelManageUser, 3, 0, 1, 1)
        self.lineEditManageUser = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditManageUser.setObjectName("lineEditManageUser")
        self.gridLayout.addWidget(self.lineEditManageUser, 3, 1, 1, 1)
        self.labelManagePassword = QtGui.QLabel(self.groupBox_3)
        self.labelManagePassword.setObjectName("labelManagePassword")
        self.gridLayout.addWidget(self.labelManagePassword, 4, 0, 1, 1)
        self.lineEditManagePassword = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditManagePassword.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEditManagePassword.setObjectName("lineEditManagePassword")
        self.gridLayout.addWidget(self.lineEditManagePassword, 4, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 2)
        self.labelAccessUser = QtGui.QLabel(self.groupBox_3)
        self.labelAccessUser.setObjectName("labelAccessUser")
        self.gridLayout.addWidget(self.labelAccessUser, 6, 0, 1, 1)
        self.lineEditAccessUser = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditAccessUser.setObjectName("lineEditAccessUser")
        self.gridLayout.addWidget(self.lineEditAccessUser, 6, 1, 1, 1)
        self.labelAccessPassword = QtGui.QLabel(self.groupBox_3)
        self.labelAccessPassword.setObjectName("labelAccessPassword")
        self.gridLayout.addWidget(self.labelAccessPassword, 7, 0, 1, 1)
        self.lineEditAccessPassword = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditAccessPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEditAccessPassword.setObjectName("lineEditAccessPassword")
        self.gridLayout.addWidget(self.lineEditAccessPassword, 7, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(207, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.labelNE.setBuddy(self.lineEditNE)
        self.labelIP.setBuddy(self.lineEditIP)
        self.labelManageUser.setBuddy(self.lineEditManageUser)
        self.labelManagePassword.setBuddy(self.lineEditManagePassword)
        self.labelAccessUser.setBuddy(self.lineEditAccessUser)
        self.labelAccessPassword.setBuddy(self.lineEditAccessPassword)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "网元设置", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOK.setText(QtGui.QApplication.translate("Dialog", "确认", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "网元信息", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNE.setText(QtGui.QApplication.translate("Dialog", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.labelIP.setText(QtGui.QApplication.translate("Dialog", "IP：", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "管理平台", None, QtGui.QApplication.UnicodeUTF8))
        self.labelManageUser.setText(QtGui.QApplication.translate("Dialog", "用户：", None, QtGui.QApplication.UnicodeUTF8))
        self.labelManagePassword.setText(QtGui.QApplication.translate("Dialog", "密码：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "接入平台", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAccessUser.setText(QtGui.QApplication.translate("Dialog", "用户：", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAccessPassword.setText(QtGui.QApplication.translate("Dialog", "密码：", None, QtGui.QApplication.UnicodeUTF8))

