# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zoomUpdate.ui'
#
# Created: Sat Oct 19 14:25:20 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1030, 599)
        MainWindow.setMinimumSize(QtCore.QSize(180, 0))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(954, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.pushButtonAddNe = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonAddNe.setObjectName("pushButtonAddNe")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.pushButtonAddNe)
        self.pushButtonDelNe = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonDelNe.setObjectName("pushButtonDelNe")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.pushButtonDelNe)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonAddVersionFile = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonAddVersionFile.setObjectName("pushButtonAddVersionFile")
        self.horizontalLayout.addWidget(self.pushButtonAddVersionFile)
        self.lineEditVersionFile = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditVersionFile.setReadOnly(True)
        self.lineEditVersionFile.setObjectName("lineEditVersionFile")
        self.horizontalLayout.addWidget(self.lineEditVersionFile)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditVersion = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditVersion.setReadOnly(True)
        self.lineEditVersion.setObjectName("lineEditVersion")
        self.horizontalLayout.addWidget(self.lineEditVersion)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.tableViewNe = QtGui.QTableView(self.groupBox_2)
        self.tableViewNe.setObjectName("tableViewNe")
        self.gridLayout.addWidget(self.tableViewNe, 2, 0, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 1, 2)
        self.groupBoxCheckOption = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxCheckOption.setCheckable(True)
        self.groupBoxCheckOption.setChecked(False)
        self.groupBoxCheckOption.setObjectName("groupBoxCheckOption")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxCheckOption)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBoxActiveSoft = QtGui.QCheckBox(self.groupBoxCheckOption)
        self.checkBoxActiveSoft.setChecked(True)
        self.checkBoxActiveSoft.setObjectName("checkBoxActiveSoft")
        self.gridLayout_3.addWidget(self.checkBoxActiveSoft, 2, 0, 1, 1)
        self.checkBoxUpdateVersionFile = QtGui.QCheckBox(self.groupBoxCheckOption)
        self.checkBoxUpdateVersionFile.setChecked(True)
        self.checkBoxUpdateVersionFile.setObjectName("checkBoxUpdateVersionFile")
        self.gridLayout_3.addWidget(self.checkBoxUpdateVersionFile, 1, 1, 1, 1)
        self.checkBoxSaveNeConfigToLocal = QtGui.QCheckBox(self.groupBoxCheckOption)
        self.checkBoxSaveNeConfigToLocal.setEnabled(False)
        self.checkBoxSaveNeConfigToLocal.setChecked(True)
        self.checkBoxSaveNeConfigToLocal.setObjectName("checkBoxSaveNeConfigToLocal")
        self.gridLayout_3.addWidget(self.checkBoxSaveNeConfigToLocal, 1, 0, 1, 1)
        self.checkBoxReboot = QtGui.QCheckBox(self.groupBoxCheckOption)
        self.checkBoxReboot.setChecked(True)
        self.checkBoxReboot.setObjectName("checkBoxReboot")
        self.gridLayout_3.addWidget(self.checkBoxReboot, 2, 1, 1, 1)
        self.checkBoxCheckUpdateFile = QtGui.QCheckBox(self.groupBoxCheckOption)
        self.checkBoxCheckUpdateFile.setEnabled(False)
        self.checkBoxCheckUpdateFile.setChecked(True)
        self.checkBoxCheckUpdateFile.setObjectName("checkBoxCheckUpdateFile")
        self.gridLayout_3.addWidget(self.checkBoxCheckUpdateFile, 0, 1, 1, 1)
        self.checkBoxSaveNeConfig = QtGui.QCheckBox(self.groupBoxCheckOption)
        self.checkBoxSaveNeConfig.setChecked(True)
        self.checkBoxSaveNeConfig.setObjectName("checkBoxSaveNeConfig")
        self.gridLayout_3.addWidget(self.checkBoxSaveNeConfig, 0, 2, 1, 1)
        self.checkBoxUpgradeSoft = QtGui.QCheckBox(self.groupBoxCheckOption)
        self.checkBoxUpgradeSoft.setChecked(True)
        self.checkBoxUpgradeSoft.setObjectName("checkBoxUpgradeSoft")
        self.gridLayout_3.addWidget(self.checkBoxUpgradeSoft, 1, 2, 1, 1)
        self.checkBoxAfterRebootConnectTest = QtGui.QCheckBox(self.groupBoxCheckOption)
        self.checkBoxAfterRebootConnectTest.setChecked(True)
        self.checkBoxAfterRebootConnectTest.setObjectName("checkBoxAfterRebootConnectTest")
        self.gridLayout_3.addWidget(self.checkBoxAfterRebootConnectTest, 2, 2, 1, 1)
        self.checkBoxCheckNe = QtGui.QCheckBox(self.groupBoxCheckOption)
        self.checkBoxCheckNe.setEnabled(False)
        self.checkBoxCheckNe.setChecked(True)
        self.checkBoxCheckNe.setObjectName("checkBoxCheckNe")
        self.gridLayout_3.addWidget(self.checkBoxCheckNe, 0, 0, 1, 1)
        self.checkBoxAfterRebootTest = QtGui.QCheckBox(self.groupBoxCheckOption)
        self.checkBoxAfterRebootTest.setChecked(True)
        self.checkBoxAfterRebootTest.setObjectName("checkBoxAfterRebootTest")
        self.gridLayout_3.addWidget(self.checkBoxAfterRebootTest, 3, 0, 1, 1)
        self.checkBoxfterRebootConfigCheck = QtGui.QCheckBox(self.groupBoxCheckOption)
        self.checkBoxfterRebootConfigCheck.setChecked(True)
        self.checkBoxfterRebootConfigCheck.setObjectName("checkBoxfterRebootConfigCheck")
        self.gridLayout_3.addWidget(self.checkBoxfterRebootConfigCheck, 3, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxCheckOption, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonCheckNe = QtGui.QPushButton(self.groupBox_3)
        self.pushButtonCheckNe.setObjectName("pushButtonCheckNe")
        self.gridLayout_2.addWidget(self.pushButtonCheckNe, 0, 0, 1, 1)
        self.textEditInformation = QtGui.QTextEdit(self.groupBox_3)
        self.textEditInformation.setMinimumSize(QtCore.QSize(0, 120))
        self.textEditInformation.setObjectName("textEditInformation")
        self.gridLayout_2.addWidget(self.textEditInformation, 0, 1, 3, 1)
        self.pushButtonUpdateAll = QtGui.QPushButton(self.groupBox_3)
        self.pushButtonUpdateAll.setObjectName("pushButtonUpdateAll")
        self.gridLayout_2.addWidget(self.pushButtonUpdateAll, 1, 0, 1, 1)
        self.pushButtonCancel = QtGui.QPushButton(self.groupBox_3)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout_2.addWidget(self.pushButtonCancel, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1030, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImportConfig = QtGui.QAction(MainWindow)
        self.actionImportConfig.setObjectName("actionImportConfig")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSaveConfig = QtGui.QAction(MainWindow)
        self.actionSaveConfig.setObjectName("actionSaveConfig")
        self.actionSaveAs = QtGui.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.menuFile.addAction(self.actionImportConfig)
        self.menuFile.addAction(self.actionSaveConfig)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "AC升级工具", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "网元信息", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddNe.setText(QtGui.QApplication.translate("MainWindow", "添加网元", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDelNe.setText(QtGui.QApplication.translate("MainWindow", "删除网元", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddVersionFile.setText(QtGui.QApplication.translate("MainWindow", "版本文件", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "版本信息", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxCheckOption.setTitle(QtGui.QApplication.translate("MainWindow", "升级选项", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxActiveSoft.setText(QtGui.QApplication.translate("MainWindow", "7.激活版本文件", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUpdateVersionFile.setText(QtGui.QApplication.translate("MainWindow", "5.上传版本文件", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxSaveNeConfigToLocal.setText(QtGui.QApplication.translate("MainWindow", "4.保存配置到本地", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxReboot.setText(QtGui.QApplication.translate("MainWindow", "8.复位", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxCheckUpdateFile.setText(QtGui.QApplication.translate("MainWindow", "2.检测版本文件", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxSaveNeConfig.setText(QtGui.QApplication.translate("MainWindow", "3.保存当前运行配置", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUpgradeSoft.setText(QtGui.QApplication.translate("MainWindow", "6.释放版本文件", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAfterRebootConnectTest.setText(QtGui.QApplication.translate("MainWindow", "9.复位后连通性检测", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxCheckNe.setText(QtGui.QApplication.translate("MainWindow", "1.检测网元", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAfterRebootTest.setText(QtGui.QApplication.translate("MainWindow", "10.升级后检测", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxfterRebootConfigCheck.setText(QtGui.QApplication.translate("MainWindow", "11.升级后配置检测", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "升级操作", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCheckNe.setText(QtGui.QApplication.translate("MainWindow", "网元检测", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonUpdateAll.setText(QtGui.QApplication.translate("MainWindow", "升级全部", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("MainWindow", "取消操作", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "文件", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "帮助", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportConfig.setText(QtGui.QApplication.translate("MainWindow", "导入配置", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "关于", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "退出", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveConfig.setText(QtGui.QApplication.translate("MainWindow", "保留配置", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "另存配置", None, QtGui.QApplication.UnicodeUTF8))

